sudo: required
language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.8
    packages:
    - g++-4.9
    - g++-5
    - g++-6
    - clang-3.8
    - gradle

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
    - compiler: gcc
      env: COMPILER=g++-5
    - compiler: gcc
      env: COMPILER=g++-6
    - compiler: clang
      env: COMPILER=clang++-3.8
    - language: java
      script:
        - gradle jar

script:
  cd raytracer && make CXX=$COMPILER
